version: "3"

services:
  frontend:
    image: front-end
    build: ./client/
    ports:
    - "8080:80"

  backend:
    image: back-end
    build: ./server/
    restart: always
    ports:
    - "5000:5000"