version: "3"

services:
  frontend:
    image: display-remote/client
    build: ./client/
    ports:
    - "8080:80"

  backend:
    image: display-remote/server
    build: ./server/
    volumes: 
      - ./store:/app/store
    ports:
    - "5000:5000"